# Generated by Django 2.1.7 on 2019-03-02 08:06

import django.db.models.deletion
import jsonfallback.fields
from django.db import migrations, models

import pretix.base.models.fields
import pretix.base.models.seating


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0112_auto_20181217_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='layout_category',
        ),
        migrations.AddField(
            model_name='seat',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='pretixbase.Item'),
        ),
    ]
